# Site Info
title: "Discovery One"
#subtile
#description
name: "Zepp"
url: "https://zepplu.github.io"
baseurl: "/"

# Appearance
remote_theme: "mmistakes/minimal-mistakes@4.17.2"
minimal_mistakes_skin: "dirt"
include:
  - _pages

# Taxonomy (GitHub pages supports liquid only)
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Default Settings for Different MarkDowns
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      comments: false  # TODO: use staticman
      share: false
      related: true
      read_time: true
  - scope:  # special pages
      path: "_pages"
      type: pages
    values:
      layout: single

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
